Q3.txt
NoorAlkattan/HW10 pull request #1
Opened 2016-10-13 00:12 UTC by NoorAlkattan

2016-10-13 16:51 UTC, ssharba requested changes

2016-10-13 16:51 UTC, ssharba commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
@NoorAlkattan can we do this with one loop?

2016-10-14 16:17 UTC, NoorAlkattan commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
Hi Samer , what do you mean by one loop?

2016-10-14 16:51 UTC, ssharba requested changes

2016-10-14 16:51 UTC, ssharba commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
you are looping through the array for each condition, I would start one loop and combine all if conditions inside it.

2016-10-14 19:51 UTC, NoorAlkattan commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];

 var i=0;
 var x=0;

 for (i=0;i<b.length;i++){
    if(b[i]%2 !==0){
        console.log(b[i]*2);
    }
        if (b[i]%2 ===0)
        console.log(b[i]-2);

```
 if(b[i]%5 === 0){
 console.log(Math.pow(b[i],2));
 }
 if(b[i]%10 === 0){
for (x=0; x<=b[i];x+=10){
    console.log (x);
}
 }
```

 }

2016-10-14 19:52 UTC, NoorAlkattan commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
please check see if that what exactly you want , so i can correct Ruby

2016-10-14 19:55 UTC, ssharba commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
yes

2016-10-14 19:59 UTC, NoorAlkattan commented on HW10/read.txt
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
so its right , do you want me to correct ruby also and push it again through github

2016-10-14 20:01 UTC, ssharba commented
yes, please.

On Fri, Oct 14, 2016 at 2:59 PM, NoorAlkattan <notifications@github.com>
wrote:

> *@NoorAlkattan* commented on this pull request.
> ------------------------------
>
> In HW10/read.txt <https://github.com/NoorAlkattan/HW10/pull/1>:
>
> > @@ -0,0 +1,101 @@
> +var b = [5, 10, 23, 10, 7, 9, 39, 16, 1, 12, 36, 20, 50];
>
> so its right , do you want me to correct ruby also and push it again
> through github
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/NoorAlkattan/HW10/pull/1>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALCrhTJj7NLxHh1xSKRLLjWcoIAYTTymks5qz98bgaJpZM4KVWlq>
> .
>

2016-10-16 00:53 UTC, closed without merging